### ISSUE TITLE
Load C# dll in Odoo module

### ISSUE THREAD

**Issue by omarouhari** [OCA/dotnet#4]
Hello,
I try to communicate my odoo module with zkteco device using a C# dll (Interop.zkemkeeper.dll). I try python_zklib but it present some limitations (can't set user cardnumber nither set user with uid > 255). In fact, I want to load the C# dll in Odoo module and use it functions (Connect_Net, SetStrCardNumber, SSR_SetUserInfo).
If necessary, I can send the dll file.
Thanks for your help.

**Comment by not-mounam** [comment]
hello,
did you find a solution to this issue ?
thanks for ur answer in advance
